### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by fragment0** [fragment0/ts-weapp#5]
- [ ] `npm run adds` -> `npm run add`
- [ ] `JSON.stringify` app.json 时加格式化
- [ ] 模板中添加对应可替换变量，保证生成文件中均有可定位的特殊关键字
- [ ] 去掉所有中文注解
- [ ] app.css 里增加初始化样式
- [ ] component.ts 错误 midi 路径
- [ ] remove postcss-calc
- [ ] 所有 css 文件自动引入 var.config.css
- [ ] 微信 definition 升级了 component 相关，与现在不兼容，要弄一下
- [ ] 两个空格
- [ ] component property observer 要增加参数参数

**Comment by juzhiyuan** [comment]
`npm run adds` -> `npm run add`

考虑到使用 `yarn` 的话，就会与 `yarn add` 冲突了。

**Comment by fragment0** [comment]
> `npm run adds` -> `npm run add`
> 
> 考虑到使用 `yarn` 的话，就会与 `yarn add` 冲突了；`create` 也被占用，我考虑一个更合适的名字。

`add-page` `add-component` 算了
